ElectricTests/Controllers/Api/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using ElectricTests.Model;
using System.Data.Entity;
using ElectricTests.Repository;

//using System.Web.Http.OData;

namespace ElectricTests.Controllers.Api
{
    public class QuestionsController : /*EntitySetController<Question, int>*/ ApiController
    {
        // GET api/questions
        public IQueryable<Question> Get()
        {
            var repository = new QuestionsRepository();
            return repository.GetAllQuestions().AsQueryable();
            //return new string[] { "value1", "value2" };
        }

        // GET api/questions/5
        public string Get(int id)
        {
            return "value";
        }

        // POST api/questions
        public void Post([FromBody]string value)
        {
        }

        // PUT api/questions/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/questions/5
        public void Delete(int id)
        {
        }
    }
}

ElectricTests/Controllers/MenuController.cs
using System.Collections.Generic;
using System.Web.Mvc;

namespace ElectricTests.Controllers
{
    public class MenuController : Controller
    {
        /// <summary>
        /// Show menu as widget, mark button with current controller
        /// </summary>
        /// <param name="controllerName"></param>
        /// <returns></returns>
        [ChildActionOnly]
        public ActionResult Show (string controllerName = null) {
            //Controller name to mark current menu button
            ViewBag.ControllerName = controllerName;
            
            //All menu buttons names with their controller names
            var menu = new Dictionary<string, string> {
                {"Pagrindinis", "Home"},
                {"Dokumentai", "Documents"},
                {"Testavimas", "Tests"},
                {"Pagalba", "Help"}
            };
            return PartialView(menu);
        }
    }
}

ElectricTests/Views/Shared/_AddQuestionForm.cshtml
@model Question
<div id="addQuestionForm" class="reveal-modal xlarge">
	@using (Html.BeginForm()) {
		@Html.ValidationSummary(true)

		<fieldset>
			<h6>Taisyklės punktas, kuris bus parodytas kaip paaiškinimas jeigu žmogus padarys klaidą atsakydamas į jūsų klausimą.</h6>
			<div id="formParagraphText"></div>
			<legend>Įveskite klausimą ir atsakymo variantus</legend>
			Klausimas
			<div>
				@Html.TextAreaFor(model => model.Title, new {rows = 4})
				@Html.ValidationMessageFor(model => model.Title)
			</div>
			Pirmas atsakymo variantas (teisingas)
			<div>
				@Html.TextAreaFor(model => model.Option1, new {rows = 4})
				@Html.ValidationMessageFor(model => model.Option1)
			</div>
			Antras atsakymo variantas (neteisingas)
			<div>
				@Html.TextAreaFor(model => model.Option2, new {rows = 4})
				@Html.ValidationMessageFor(model => model.Option2)
			</div>
			Trečias atsakymo variantas (neteisingas, nebūtinas)
			<div>
				@Html.TextAreaFor(model => model.Option3, new {rows = 4})
				@Html.ValidationMessageFor(model => model.Option3)
			</div>
			Ketvirtas atsakymo variantas (neteisingas, nebūtinas)
			<div>
				@Html.TextAreaFor(model => model.Option4, new {rows = 4})
				@Html.ValidationMessageFor(model => model.Option4)
			</div>
			@Html.HiddenFor(model => model.FormattedDocumentId)
			@Html.HiddenFor(model => model.ParagraphId)
			<input value="Įkelti klausymą" class="button" onclick="validateAndSendObject($('form').serialize(), false);"/>
            <input value="Test" class="button" onclick="modal();"/>
		</fieldset>
	}		
	<a class="close-reveal-modal">x</a>
</div>
<script type="text/javascript">
	function sendQuestion(question) {
		$.ajax({
			url: '@Url.Action("Add", "Questions")'
		, type: 'POST'
		, data: question
		, success: function (savedToDB) {
		    $("#addQuestionForm").reveal();
			$("#infoMessageWindow").reveal();
		}
	});
	}

    function modal() {
        $("#addQuestionForm").reveal();
        $("#infoMessageWindow").show();
    }
</script>

ElectricTests/Views/Shared/_AddQuestionFormWithoutParagraph.cshtml
@model Question
<div id="addQuestionFormWithoutParagraph" class="reveal-modal xlarge">
	@using (Html.BeginForm()) {
		@Html.ValidationSummary(true)

		<fieldset>
			<h6>Taisyklės punktas</h6>
			<p id="formParagraphText"></p>
			<legend>Įveskite klausimą ir atsakymo variantus</legend>
			Klausimas
			<div>
				@Html.TextAreaFor(model => model.Title, new {rows = 4})
				@Html.ValidationMessageFor(model => model.Title)
			</div>
			Pirmas atsakymo variantas (teisingas)
			<div>
				@Html.TextAreaFor(model => model.Option1, new {rows = 4})
				@Html.ValidationMessageFor(model => model.Option1)
			</div>
			Antras atsakymo variantas
			<div>
				@Html.TextAreaFor(model => model.Option2, new {rows = 4})
				@Html.ValidationMessageFor(model => model.Option2)
			</div>
			Trečias atsakymo variantas (nebūtinas)
			<div>
				@Html.TextAreaFor(model => model.Option3, new {rows = 4})
				@Html.ValidationMessageFor(model => model.Option3)
			</div>
			Ketvirtas atsakymo variantas (nebūtinas)
			<div>
				@Html.TextAreaFor(model => model.Option4, new {rows = 4})
				@Html.ValidationMessageFor(model => model.Option4)
			</div>
			Klausimo paaiškinimas
			<div>
				@Html.TextAreaFor(model => model.AnswerDescription, new {rows = 4})
				@Html.ValidationMessageFor(model => model.AnswerDescription)
			</div>
			<input value="Įkelti klausymą" class="button" onclick="validateAndSendObject($('form').serialize(), true);"/>
		</fieldset>
	}		
	<a class="close-reveal-modal">x</a>
</div>
<script type="text/javascript">
	function sendQuestion(question) {
		$.ajax({
			url: '@Url.Action("Add", "Questions")'
		, type: 'POST'
		, data: question
		, success: function (savedToDB) {
			$("#infoMessageWindow").reveal();
		}
	});
}
</script>

ElectricTests/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="lt">
	<head>
		<meta charset="utf-8" />
		<title>@ViewBag.Title - My ASP.NET MVC Application</title>
		<link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
		<meta name="viewport" content="width=device-width" />
		@Styles.Render("~/Content/stylesheets/foundation.min.css")
		@Styles.Render("~/Content/stylesheets/app.css")
		@Scripts.Render("~/Content/javascripts/modernizr.foundation.js")
	</head>
	<body>
		<div class="container">
			<header>
				<div class="row">
					<div class="three columns">
						<a href="@Url.Action("Index", "Home")"><img src="@Url.Content("~/Content/images/shock.png")" alt="Home" /></a>

					</div>
					<div class="nine columns">
						@Html.Action("Show", "Menu", 
						new {ControllerName = HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString()})
					</div>
				</div>
			</header>
			<div class="row">
				@RenderSection("featured", required: false)
				@RenderBody()
			</div>
		</div>
		<footer class="row footer">
			<div class="twelve columns">
				<div class="six columns">
					<p>© Aleksandr Suchovarov, 2013</p>
				</div>
				<div class="six columns">
					@if (Request.IsAuthenticated) {
						using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" })) {
							@Html.AntiForgeryToken()
							<ul class="link-list right">
                                <li>@Html.ActionLink("Nustatymai", "Manage", "Account")</li>
                                @if(Roles.IsUserInRole("Administrator")) {
                                    <li>@Html.ActionLink("Klausimai", "Index", "Questions")</li>
                                }
								<li><a href="javascript:document.getElementById('logoutForm').submit()">Išeiti</a></li>
							</ul>
						}
						
					} else {
						<ul class="link-list right">
							<li>@Html.ActionLink("Įeiti", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
						</ul>
					}
				</div>
			</div>
		</footer>
		@Scripts.Render("~/Content/javascripts/jquery.js")
		@RenderSection("scripts", required: false)
	</body>
</html>

ElectricTests/Views/Shared/_ShowQuestionInTest.cshtml
@model ElectricTests.Model.Question
<div class="questionInTest" id="@Model.Id">
	<h4>@Html.DisplayFor(model => model.Title)</h4>
	<div id="options">
			<div class="testOption" onclick="selectOption(1);" id="option1">
				@Html.Raw(@Model.Option1.Replace("\r\n", "<br />"))
			</div>
			<div class="testOption" onclick="selectOption(2);" id="option2">
				@Html.Raw(@Model.Option2.Replace("\r\n", "<br />"))
			</div>
			@if (Model.Option3 != null) {
				<div class="testOption" onclick="selectOption(3);" id="option3">
				@Html.Raw(@Model.Option3.Replace("\r\n", "<br />"))
				</div>
			}
			@if (Model.Option4 != null) {
			<div class="testOption" onclick="selectOption(4);" id="option4">
				@Html.Raw(@Model.Option4.Replace("\r\n", "<br />"))
			</div>
			}
		</div>
</div>

ElectricTests/Views/Shared/_infoMessageWindow.cshtml
@model string
<div id="infoMessageWindow" class="reveal-modal">
	<p id="infoMessage">@Model</p>
	<button class="close-reveal-modal button" id="">Ok</button>
</div>